[package]
name = "tmpl-hypertext"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"
publish = false

[dependencies]
hypertext.git = "https://github.com/vidhanio/hypertext"
tmpls = { version = "*", path = ".." }

